stages:
  - pruebas
  - despliegue

test-job:
  stage: pruebas
  script:
    - cd ~/public_html
    - git pull origin master
    - php artisan migrate:fresh
    - php artisan test
  tags:
    - seminario

deploy-job:
  stage: despliegue
  script:
    - cd ~/public_html
    - git pull origin master
    - sh ~/permisos.sh
  tags:
    - seminario
